name: PufferPanel

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write   # Required to push changes back

concurrency:
  group: pufferpanel
  cancel-in-progress: true

jobs:
  pufferpanel:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      # --- Checkout repository ---
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      # --- Install Docker Compose ---
      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE=/usr/local/bin/docker-compose
          if ! command -v docker-compose &> /dev/null; then
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o $DOCKER_COMPOSE
            sudo chmod +x $DOCKER_COMPOSE
          fi
          docker-compose --version

      # --- Restore latest PufferPanel backup if exists ---
      - name: Restore latest backup
        run: |
          echo "Checking for previous backups..."
          git fetch origin main
          git checkout origin/main -- pufferpanel_*.tar.gz.part-* || echo "No previous backup found"

          if ls pufferpanel_*.tar.gz.part-* 1> /dev/null 2>&1; then
            echo "Found backup parts. Reconstructing backup..."
            cat pufferpanel_*.tar.gz.part-* > pufferpanel.tar.gz
            rm -rf pufferpanel
            mkdir -p pufferpanel
            tar -xzf pufferpanel.tar.gz -C .
            echo "Backup restored successfully."
          else
            echo "No backup found. Starting fresh."
            mkdir -p pufferpanel
          fi

      # --- Create Docker Compose file ---
      - name: Create Docker Compose for PufferPanel
        run: |
          cat > pufferpanel/docker-compose.yml <<'EOF'
          version: '3.8'
          services:
            pufferpanel:
              image: pufferpanel/pufferpanel:latest
              container_name: pufferpanel
              restart: unless-stopped
              ports:
                - "8080:8080"
                - "5657:5657"
              volumes:
                - ./config:/etc/pufferpanel
                - ./data:/var/lib/pufferpanel
              environment:
                PUFFER_ADMIN_EMAIL: "admin@example.com"
          EOF

      # --- Start PufferPanel Container ---
      - name: Start PufferPanel Container
        run: |
          cd pufferpanel
          docker-compose up -d

      # --- Create Admin User ---
      - name: Create Admin User
        run: |
          docker exec pufferpanel /pufferpanel/pufferpanel user add \
            --name kshosting \
            --email kshosting@ksmail.com \
            --password kshosting@55 \
            --admin || echo "Admin user may already exist"

      # --- Install tmate ---
      - name: Install tmate
        run: sudo apt-get update && sudo apt-get install -y tmate

      # --- Start tmate session (keep alive) ---
      - name: Start tmate session
        run: |
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          echo "SSH access:"
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          echo "Web access:"
          tmate -S /tmp/tmate.sock display -p '#{tmate_web}'
          sleep 20000  # Keep workflow alive

      # --- Backup and commit PufferPanel data ---
      - name: Backup and Commit PufferPanel Data
        if: ${{ always() }}
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          BACKUP_NAME="pufferpanel_${TIMESTAMP}.tar.gz"
          echo "Cleaning old backups..."
          git ls-files -z "pufferpanel_*.tar.gz.part-*" | xargs -0 git rm -f || true
          echo "Creating new backup: $BACKUP_NAME"
          tar -czf - pufferpanel | split -b 90M - "${BACKUP_NAME}.part-"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ${BACKUP_NAME}.part-*
          git commit -m "Backup PufferPanel data ($TIMESTAMP)" || echo "Nothing to commit"
          git push origin main || echo "Nothing to push"

      # --- Auto-restart workflow ---
      - name: Restart Workflow
        if: ${{ always() }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: PufferPanel
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
